---
time_zone: US/Pacific
jenkins:
  key_url: https://pkg.jenkins.io/debian/jenkins.io.key
  repo: deb http://pkg.jenkins.io/debian-stable binary/
  user: jenkins
  groups:
    - jenkins
    - docker
  uid: 1040
ansible:
  repo: ppa:ansible/ansible
docker:
  key_url: https://download.docker.com/linux/ubuntu/gpg
  repo: "deb [arch=armhf] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
