---
- hosts: jenkins
  become: true
  become_method: sudo
  vars:
    jenkins:
      key: https://pkg.jenkins.io/debian/jenkins.io.key
      repo: deb http://pkg.jenkins.io/debian-stable binary/

  tasks:

    - name: Install java8
      apt:
        name: openjdk-8-jre
        state: present
      tags:
        - java

    - name: Add apt signing key for Jenkins
      apt_key:
        url: "{{ jenkins.key }}"
        state: present

    - name: Add apt repository for Jenkins
      apt_repository:
        repo: "{{ jenkins.repo }}"
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        update_cache: yes

    - name: Cat password to debug
      debug:
        msg: /var/lib/jenkins/secrets/initialAdminPassword

    - name: Cat admin pass
      command: "cat /var/lib/jenkins/secrets/initialAdminPassword"
      register: admin_pass

    - name: Display admin pass
      debug: msg={{ admin_pass.stdout }}
