---
- hosts: local,jenkins
  become: true
  become_method: sudo
  vars:
    jenkins:
      key_url: https://pkg.jenkins.io/debian/jenkins.io.key
      repo: deb http://pkg.jenkins.io/debian-stable binary/
      user: jenkins
      group: jenkins
      uid: 1040
    ansible:
      key_server: keyserver.ubuntu.com 
      key_id: 93C4A3FD7BB9C367

  tasks:

    ###################
    # Install Jenkins #
    ###################

    - name: Install java8
      apt:
        name: openjdk-8-jre
        state: present
      tags:
        - java

    - name: Add apt signing key for Jenkins
      apt_key:
        url: "{{ jenkins.key_url }}"
        state: present

    - name: Add apt repository for Jenkins
      apt_repository:
        repo: "{{ jenkins.repo }}"
        state: present

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes

#     - name: Cat password to debug
#       debug:
#         msg: /var/lib/jenkins/secrets/initialAdminPassword

#     - name: Cat admin pass
#       command: "cat /var/lib/jenkins/secrets/initialAdminPassword"
#       register: admin_pass

#     - name: Display admin pass
#       debug: msg={{ admin_pass.stdout }}
#       when: admin_pass

    ###################
    # Install ansible #
    ###################
    
    # apt-add-repository "deb http://ppa.launchpad.net/ansible/ansible/ubuntu bionic main"

    - name: Add apt signing key for Ansible
      apt_key:
        keyserver: "{{ ansible.key_server }}"
        id: "{{ ansible.key_id }}"
        state: present

    - name: Enable Ansible repository
      apt_repository:
        repo: "deb http://ppa.launchpad.net/ansible/ansible/ubuntu {{ ansible_distribution_release }} main"
        state: present

    - name: Install Ansible
      apt:
        name: ansible
        state: present
        update_cache: yes

    #############################
    # Add Jenkins user to hosts #
    #############################
    
- hosts: all
  become: true
  become_method: sudo
  tasks:

    - name: Ensure group jenkins exists
      group:
        name: "{{ jenkins.user }}"
        state: present

    - name: Add Jenkins user to all hosts
      user:
        name: "{{ jenkins.user }}"
        uid: "{{ jenkins.uid }}"
        group: "{{ jenkins.group }}"
